services:
  - type: web
    name: backend
    runtime: node
    rootDir: backend
    buildCommand: cd backend;  npm run build;
    startCommand: npm run start
  - type: web
    name: frontend
    runtime: node
    buildCommand: cd frontend; npm run build;
    startCommand: npm run start
